In [1]:
import duckdb
import pandas as pd

con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')

# Look at game_teams_stats
df = con.execute("SELECT * FROM raw.game_teams_stats LIMIT 10").fetchdf()
df

,game_id,team_id,HoA,won,settled_in,head_coach,goals,shots,hits,pim,powerPlayOpportunities,powerPlayGoals,faceOffWinPercentage,giveaways,takeaways,blocked,startRinkSide
0,2016020045,4,away,False,REG,Dave Hakstol,4,27,30,6,4,2,50.9,12,9,11,left
1,2016020045,16,home,True,REG,Joel Quenneville,7,28,20,8,3,2,49.1,16,8,9,left
2,2017020812,24,away,True,OT,Randy Carlyle,4,34,16,6,3,1,43.8,7,4,14,right
3,2017020812,7,home,False,OT,Phil Housley,3,33,17,8,2,1,56.2,5,6,14,right
4,2015020314,21,away,True,REG,Patrick Roy,4,29,17,9,3,1,45.7,13,5,20,left
5,2015020314,52,home,False,REG,Paul Maurice,1,21,22,11,2,0,54.3,13,7,9,left
6,2015020849,52,away,False,REG,Paul Maurice,1,21,21,10,4,0,31.4,4,14,16,left
7,2015020849,12,home,True,REG,Bill Peters,2,29,16,8,5,2,68.6,12,11,13,left
8,2017020586,20,away,False,REG,Glen Gulutzan,1,23,20,19,3,0,54.7,10,4,7,right
9,2017020586,24,home,True,REG,Randy Carlyle,2,41,15,13,6,1,45.3,13,4,21,right

In [2]:
# Column names and types
print(df.dtypes)
print()
# Null counts
print(con.execute("SELECT * FROM raw.game_teams_stats LIMIT 1000").fetchdf().isnull().sum())

game_id                     int64
team_id                     int64
HoA                           str
won                          bool
settled_in                    str
head_coach                    str
goals                       int64
shots                       int64
hits                        int64
pim                         int64
powerPlayOpportunities      int64
powerPlayGoals              int64
faceOffWinPercentage      float64
giveaways                   int64
takeaways                   int64
blocked                     int64
startRinkSide                 str
dtype: object

game_id                    0
team_id                    0
HoA                        0
won                        0
settled_in                 0
head_coach                 0
goals                      0
shots                      0
hits                       4
pim                        0
powerPlayOpportunities     0
powerPlayGoals             0
faceOffWinPercentage       4
giveaways                  4
takeaways                  4
blocked                    4
startRinkSide             11
dtype: int64

In [3]:
# What does HoA contain?
print(con.execute("SELECT DISTINCT HoA FROM raw.game_teams_stats").fetchdf())

# What does settled_in contain?
print(con.execute("SELECT DISTINCT settled_in FROM raw.game_teams_stats").fetchdf())

    HoA
0  away
1  home
  settled_in
0        tbc
1         OT
2        REG

In [5]:
con.close()

In [2]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
df = con.execute("SELECT * FROM raw.team_info LIMIT 10").fetchdf()
df

,team_id,franchiseId,shortName,teamName,abbreviation,link
0,1,23,New Jersey,Devils,NJD,/api/v1/teams/1
1,4,16,Philadelphia,Flyers,PHI,/api/v1/teams/4
2,26,14,Los Angeles,Kings,LAK,/api/v1/teams/26
3,14,31,Tampa Bay,Lightning,TBL,/api/v1/teams/14
4,6,6,Boston,Bruins,BOS,/api/v1/teams/6
5,3,10,NY Rangers,Rangers,NYR,/api/v1/teams/3
6,5,17,Pittsburgh,Penguins,PIT,/api/v1/teams/5
7,17,12,Detroit,Red Wings,DET,/api/v1/teams/17
8,28,29,San Jose,Sharks,SJS,/api/v1/teams/28
9,18,34,Nashville,Predators,NSH,/api/v1/teams/18

In [3]:
print(df.dtypes)
print()
# Check for extra spaces in string columns
print(df['shortName'].unique())
print(df['teamName'].unique())

team_id         int64
franchiseId     int64
shortName         str
teamName          str
abbreviation      str
link              str
dtype: object

<ArrowStringArray>
[  'New Jersey', 'Philadelphia',  'Los Angeles',    'Tampa Bay',
       'Boston',   'NY Rangers',   'Pittsburgh',      'Detroit',
     'San Jose',    'Nashville']
Length: 10, dtype: str
<ArrowStringArray>
[   'Devils',    'Flyers',     'Kings', 'Lightning',    'Bruins',   'Rangers',
  'Penguins', 'Red Wings',    'Sharks', 'Predators']
Length: 10, dtype: str

In [3]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
df = con.execute("SELECT * FROM raw.game_skater_stats LIMIT 10").fetchdf()
print(df.dtypes)
df

game_id                 int64
player_id               int64
team_id                 int64
timeOnIce               int64
assists                 int64
goals                   int64
shots                   int64
hits                    int64
powerPlayGoals          int64
powerPlayAssists        int64
penaltyMinutes          int64
faceOffWins             int64
faceoffTaken            int64
takeaways               int64
giveaways               int64
shortHandedGoals        int64
shortHandedAssists      int64
blocked                 int64
plusMinus               int64
evenTimeOnIce           int64
shortHandedTimeOnIce    int64
powerPlayTimeOnIce      int64
dtype: object

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
0,2016020045,8468513,4,955,1,0,0,2,0,0,...,0,1,1,0,0,1,1,858,97,0
1,2016020045,8476906,4,1396,1,0,4,2,0,0,...,0,1,2,0,0,2,0,1177,0,219
2,2016020045,8474668,4,915,0,0,1,1,0,0,...,0,2,0,0,0,0,-1,805,0,110
3,2016020045,8473512,4,1367,3,0,0,0,0,2,...,27,0,0,0,0,0,-1,1083,19,265
4,2016020045,8471762,4,676,0,0,3,2,0,0,...,0,0,1,0,0,0,-1,613,63,0
5,2016020045,8478439,4,1008,1,0,2,0,0,0,...,0,1,0,0,0,0,-1,911,0,97
6,2016020045,8479648,4,630,0,0,0,2,0,0,...,0,0,0,0,0,0,-1,630,0,0
7,2016020045,8470159,4,409,0,0,0,0,0,0,...,7,1,0,0,0,0,-1,360,49,0
8,2016020045,8478500,4,1275,0,0,0,1,0,0,...,0,0,1,0,0,0,-5,1015,139,121
9,2016020045,8475430,4,1029,0,0,1,5,0,0,...,0,0,1,0,0,1,1,988,41,0

In [4]:
print(df.dtypes)
print()
print(df.isnull().sum())

game_id                 int64
player_id               int64
team_id                 int64
timeOnIce               int64
assists                 int64
goals                   int64
shots                   int64
hits                    int64
powerPlayGoals          int64
powerPlayAssists        int64
penaltyMinutes          int64
faceOffWins             int64
faceoffTaken            int64
takeaways               int64
giveaways               int64
shortHandedGoals        int64
shortHandedAssists      int64
blocked                 int64
plusMinus               int64
evenTimeOnIce           int64
shortHandedTimeOnIce    int64
powerPlayTimeOnIce      int64
dtype: object

game_id                 0
player_id               0
team_id                 0
timeOnIce               0
assists                 0
goals                   0
shots                   0
hits                    0
powerPlayGoals          0
powerPlayAssists        0
penaltyMinutes          0
faceOffWins             0
faceoffTaken            0
takeaways               0
giveaways               0
shortHandedGoals        0
shortHandedAssists      0
blocked                 0
plusMinus               0
evenTimeOnIce           0
shortHandedTimeOnIce    0
powerPlayTimeOnIce      0
dtype: int64

In [1]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
print(con.execute("DESCRIBE raw.game_plays").fetchdf().to_string())

            column_name column_type null   key default extra
0               play_id     VARCHAR  YES  None    None  None
1               game_id      BIGINT  YES  None    None  None
2           team_id_for      BIGINT  YES  None    None  None
3       team_id_against      BIGINT  YES  None    None  None
4                 event     VARCHAR  YES  None    None  None
5         secondaryType     VARCHAR  YES  None    None  None
6                     x      BIGINT  YES  None    None  None
7                     y      BIGINT  YES  None    None  None
8                period      BIGINT  YES  None    None  None
9            periodType     VARCHAR  YES  None    None  None
10           periodTime      BIGINT  YES  None    None  None
11  periodTimeRemaining      BIGINT  YES  None    None  None
12             dateTime     VARCHAR  YES  None    None  None
13           goals_away      BIGINT  YES  None    None  None
14           goals_home      BIGINT  YES  None    None  None
15          description     VARCHAR  YES  None    None  None
16                 st_x      BIGINT  YES  None    None  None
17                 st_y      BIGINT  YES  None    None  None

In [2]:
print(con.execute("""
    SELECT * FROM raw.game_plays 
    WHERE event IN ('Shot', 'Goal', 'Penalty') 
    LIMIT 5
""").fetchdf().to_string())

         play_id     game_id  team_id_for  team_id_against event secondaryType   x   y  period periodType  periodTime  periodTimeRemaining             dateTime  goals_away  goals_home                                                                    description  st_x  st_y
0   2016020045_5  2016020045           16                4  Shot    Wrist Shot -71   9       1    REGULAR          54                 1146  2016-10-19 01:41:44           0           0                             Artem Anisimov Wrist Shot saved by Michal Neuvirth    71    -9
1   2016020045_6  2016020045           16                4  Goal   Wrap-around -88   5       1    REGULAR          56                 1144  2016-10-19 01:41:48           0           1  Patrick Kane (1) Wrap-around, assists: Artem Anisimov (2), Brent Seabrook (2)    88    -5
2   2016020045_8  2016020045            4               16  Shot    Wrist Shot  56  -7       1    REGULAR          69                 1131  2016-10-19 01:42:41           0           1                                  Dale Weise Wrist Shot saved by Corey Crawford    56    -7
3  2016020045_12  2016020045           16                4  Shot     Slap Shot -37 -24       1    REGULAR         133                 1067  2016-10-19 01:43:45           0           1                                Duncan Keith Slap Shot saved by Michal Neuvirth    37    24
4  2016020045_17  2016020045            4               16  Shot    Wrist Shot  57 -20       1    REGULAR         168                 1032  2016-10-19 01:44:54           0           1                              Wayne Simmonds Wrist Shot saved by Corey Crawford    57   -20

In [3]:
print(con.execute("""
    SELECT play_id, game_id, team_id_for, team_id_against, event, period, periodType, periodTime, goals_away, goals_home, st_x, st_y FROM raw.game_plays 
    WHERE event IN ('Shot', 'Goal', 'Penalty') 
    LIMIT 5
""").fetchdf().to_string())

         play_id     game_id  team_id_for  team_id_against event  period periodType  periodTime  goals_away  goals_home  st_x  st_y
0   2016020045_5  2016020045           16                4  Shot       1    REGULAR          54           0           0    71    -9
1   2016020045_6  2016020045           16                4  Goal       1    REGULAR          56           0           1    88    -5
2   2016020045_8  2016020045            4               16  Shot       1    REGULAR          69           0           1    56    -7
3  2016020045_12  2016020045           16                4  Shot       1    REGULAR         133           0           1    37    24
4  2016020045_17  2016020045            4               16  Shot       1    REGULAR         168           0           1    57   -20

In [1]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
print(con.execute("DESCRIBE raw.game_penalties").fetchdf().to_string())

       column_name column_type null   key default extra
0          play_id     VARCHAR  YES  None    None  None
1  penaltySeverity     VARCHAR  YES  None    None  None
2   penaltyMinutes      BIGINT  YES  None    None  None

In [2]:
df = con.execute("SELECT * FROM raw.game_penalties LIMIT 10").fetchdf()
df

          play_id penaltySeverity  penaltyMinutes
0   2016020045_41           Minor               2
1  2016020045_101           Minor               2
2  2016020045_134           Minor               2
3  2016020045_174           Minor               2
4  2016020045_189           Minor               2
5  2016020045_226           Minor               2
6  2016020045_264           Minor               2
7   2017020812_17           Minor               2
8   2017020812_59           Minor               2
9   2017020812_84           Minor               2

In [2]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
print(con.execute("DESCRIBE raw.player_info").fetchdf().to_string())

           column_name column_type null   key default extra
0            player_id      BIGINT  YES  None    None  None
1            firstName     VARCHAR  YES  None    None  None
2             lastName     VARCHAR  YES  None    None  None
3          nationality     VARCHAR  YES  None    None  None
4            birthCity     VARCHAR  YES  None    None  None
5      primaryPosition     VARCHAR  YES  None    None  None
6            birthDate     VARCHAR  YES  None    None  None
7   birthStateProvince     VARCHAR  YES  None    None  None
8               height     VARCHAR  YES  None    None  None
9            height_cm      DOUBLE  YES  None    None  None
10              weight      BIGINT  YES  None    None  None
11       shootsCatches     VARCHAR  YES  None    None  None

In [3]:
print(con.execute("SELECT * FROM raw.player_info LIMIT 5").fetchdf().to_string())

   player_id firstName      lastName nationality       birthCity primaryPosition            birthDate birthStateProvince  height  height_cm  weight shootsCatches
0    8466148    Marian         Hossa         SVK   Stará Lubovna              RW  1979-01-12 00:00:00                NaN   6' 1"     185.42     207             L
1    8465058    Michal      Rozsival         CZE          Vlasim               D  1978-09-03 01:00:00                NaN   6' 1"     185.42     210             R
2    8476906    Shayne  Gostisbehere         USA  Pembroke Pines               D  1993-04-20 01:00:00                 FL  5' 11"     180.34     180             L
3    8466285     Brian      Campbell         CAN       Strathroy               D  1979-05-23 01:00:00                 ON  5' 10"     177.80     192             L
4    8470607     Brent      Seabrook         CAN        Richmond               D  1985-04-20 01:00:00                 BC   6' 3"     190.50     220             R

In [1]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')

# Check what game_teams_stats staging looks like
df = con.execute("""
    SELECT * FROM main_staging.stg_game_teams_stats LIMIT 5
""").fetchdf()
print(df.columns.tolist())
df

['game_id', 'team_id', 'is_home', 'won', 'settled_in', 'goals', 'shots', 'hits', 'pim', 'pp_opportunities', 'pp_goals', 'pp_conversion_rate', 'face_off_win_perc', 'giveaways', 'takeaways', 'start_rink_side']

,game_id,team_id,is_home,won,settled_in,goals,shots,hits,pim,pp_opportunities,pp_goals,pp_conversion_rate,face_off_win_perc,giveaways,takeaways,start_rink_side
0,2016020045,4,False,False,REG,4,27,30,6,4,2,0.500000,50.900002,12,9,left
1,2016020045,16,True,True,REG,7,28,20,8,3,2,0.666667,49.099998,16,8,left
2,2017020812,24,False,True,OT,4,34,16,6,3,1,0.333333,43.799999,7,4,right
3,2017020812,7,True,False,OT,3,33,17,8,2,1,0.500000,56.200001,5,6,right
4,2015020314,21,False,True,REG,4,29,17,9,3,1,0.333333,45.700001,13,5,left

In [2]:
# Check what game_teams_stats staging looks like
df = con.execute("""
    SELECT * FROM main_staging.stg_game LIMIT 5
""").fetchdf()
print(df.columns.tolist())
df

['game_id', 'season', 'season_year', 'game_type', 'game_timestamp', 'away_team_id', 'home_team_id', 'away_goals', 'home_goals', 'winner', 'period_type', 'is_tbc', 'is_allstar']

,game_id,season,season_year,game_type,game_timestamp,away_team_id,home_team_id,away_goals,home_goals,winner,period_type,is_tbc,is_allstar
0,2016020045,20162017,2016,R,2016-10-19 00:30:00,4,16,4,7,home,REG,False,False
1,2017020812,20172018,2017,R,2018-02-07 00:00:00,24,7,4,3,away,OT,False,False
2,2015020314,20152016,2015,R,2015-11-24 01:00:00,21,52,4,1,away,REG,False,False
3,2015020849,20152016,2015,R,2016-02-17 00:00:00,52,12,1,2,home,REG,False,False
4,2017020586,20172018,2017,R,2017-12-30 03:00:00,20,24,1,2,home,REG,False,False

In [8]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
con.execute("SELECT schema_name, table_name FROM duckdb_tables()").fetchdf()

   schema_name         table_name
0   main_marts  mart_team_traject
1  main_silver          fact_play
2          raw               game
3          raw     game_penalties
4          raw         game_plays
5          raw  game_skater_stats
6          raw   game_teams_stats
7          raw        player_info
8          raw          team_info

In [9]:
con.execute("SELECT * FROM main_marts.mart_team_traject ORDER BY team_id, season_year").fetchdf()

,team_id,season_year,games_played,wins,win_pct,avg_goals_for,avg_shots
0,1,2000,70,48,68.6,3.80,31.27
1,1,2001,73,41,56.2,2.53,29.37
2,1,2002,72,46,63.9,2.68,31.31
3,1,2003,70,43,61.4,2.66,29.41
4,1,2005,82,46,56.1,2.84,29.21
...,...,...,...,...,...,...,...
568,53,2018,328,156,47.6,2.55,30.74
569,53,2019,316,148,46.8,2.68,31.05
570,54,2017,102,64,62.7,3.19,32.51
571,54,2018,356,184,51.7,3.04,34.37
572,54,2019,364,204,56.0,3.09,34.87

In [1]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
con.execute("DESCRIBE main_staging.stg_game").fetchdf()

       column_name column_type null   key default extra
0          game_id      BIGINT  YES  None    None  None
1           season     INTEGER  YES  None    None  None
2      season_year     INTEGER  YES  None    None  None
3        game_type     VARCHAR  YES  None    None  None
4   game_timestamp   TIMESTAMP  YES  None    None  None
5            venue     VARCHAR  YES  None    None  None
6     away_team_id     INTEGER  YES  None    None  None
7     home_team_id     INTEGER  YES  None    None  None
8       away_goals     INTEGER  YES  None    None  None
9       home_goals     INTEGER  YES  None    None  None
10          winner     VARCHAR  YES  None    None  None
11     period_type     VARCHAR  YES  None    None  None
12          is_tbc     BOOLEAN  YES  None    None  None
13      is_allstar     BOOLEAN  YES  None    None  None

In [3]:
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
con.execute("SELECT * FROM main_marts.mart_venue_advtg").fetchdf()

,venue,season_year,home_games,home_wins,home_win_pct,avg_home_goals,avg_away_goals
0,MTS Centre,2016,40,22,55.00,3.28,3.00
1,Rogers Arena,2017,41,16,39.02,2.90,3.41
2,Heinz Field,2016,1,1,100.00,4.00,2.00
3,Wells Fargo Center,2014,41,23,56.10,2.95,2.49
4,Honda Center,2013,48,33,68.75,3.40,2.38
...,...,...,...,...,...,...,...
623,Scotiabank Saddledome,2019,66,32,48.48,3.12,3.39
624,Little Caesars Arena,2019,74,24,32.43,2.11,3.43
625,Nationwide Arena,2018,92,50,54.35,3.17,2.98
626,Barclays Center,2018,44,24,54.55,3.00,2.41
627,Prudential Center,2018,80,38,47.50,2.83,2.80

In [4]:
# Check what fact_play looks like
df = con.execute("""
    SELECT * FROM main_silver.fact_play LIMIT 5
""").fetchdf()
print(df.columns.tolist())
df

['play_id', 'game_id', 'team_id_for', 'team_id_against', 'event', 'secondary_type', 'coord_x', 'coord_y', 'period', 'play_period_type', 'period_time', 'event_datetime', 'goals_away', 'goals_home', 'season', 'season_year', 'game_type', 'game_timestamp', 'winner', 'game_period_type', 'home_team_id', 'away_team_id', 'penalty_severity', 'penalty_minutes']

,play_id,game_id,team_id_for,team_id_against,event,secondary_type,coord_x,coord_y,period,play_period_type,...,season,season_year,game_type,game_timestamp,winner,game_period_type,home_team_id,away_team_id,penalty_severity,penalty_minutes
0,2016020045_5,2016020045,16,4,Shot,Wrist Shot,71,-9,1,REGULAR,...,20162017,2016,R,2016-10-19 00:30:00,home,REG,16,4,None,<NA>
1,2016020045_6,2016020045,16,4,Goal,Wrap-around,88,-5,1,REGULAR,...,20162017,2016,R,2016-10-19 00:30:00,home,REG,16,4,None,<NA>
2,2016020045_8,2016020045,4,16,Shot,Wrist Shot,56,-7,1,REGULAR,...,20162017,2016,R,2016-10-19 00:30:00,home,REG,16,4,None,<NA>
3,2016020045_9,2016020045,16,4,Takeaway,NaN,-11,-21,1,REGULAR,...,20162017,2016,R,2016-10-19 00:30:00,home,REG,16,4,None,<NA>
4,2016020045_12,2016020045,16,4,Shot,Slap Shot,37,24,1,REGULAR,...,20162017,2016,R,2016-10-19 00:30:00,home,REG,16,4,None,<NA>

In [6]:
# Check what stg_game looks like
df = con.execute("""
    SELECT * FROM main_staging.stg_game LIMIT 5
""").fetchdf()
print(df.columns.tolist())
df

['game_id', 'season', 'season_year', 'game_type', 'game_timestamp', 'venue', 'away_team_id', 'home_team_id', 'away_goals', 'home_goals', 'winner', 'period_type', 'is_tbc', 'is_allstar']

,game_id,season,season_year,game_type,game_timestamp,venue,away_team_id,home_team_id,away_goals,home_goals,winner,period_type,is_tbc,is_allstar
0,2016020045,20162017,2016,R,2016-10-19 00:30:00,United Center,4,16,4,7,home,REG,False,False
1,2017020812,20172018,2017,R,2018-02-07 00:00:00,KeyBank Center,24,7,4,3,away,OT,False,False
2,2015020314,20152016,2015,R,2015-11-24 01:00:00,MTS Centre,21,52,4,1,away,REG,False,False
3,2015020849,20152016,2015,R,2016-02-17 00:00:00,PNC Arena,52,12,1,2,home,REG,False,False
4,2017020586,20172018,2017,R,2017-12-30 03:00:00,Honda Center,20,24,1,2,home,REG,False,False

In [1]:
# Check what fact_play filtered to penalties looks like
import duckdb
con = duckdb.connect('/home/yanhan/projects/nhl-practice/nhl_raw.duckdb')
df = con.execute("""
    SELECT * FROM main_silver.fact_play  WHERE event='Penalty' LIMIT 5
""").fetchdf()
print(df.columns.tolist())
df

['play_id', 'game_id', 'team_id_for', 'team_id_against', 'event', 'secondary_type', 'coord_x', 'coord_y', 'period', 'play_period_type', 'period_time', 'event_datetime', 'goals_away', 'goals_home', 'season', 'season_year', 'game_type', 'game_timestamp', 'winner', 'game_period_type', 'home_team_id', 'away_team_id', 'penalty_severity', 'penalty_minutes']

,play_id,game_id,team_id_for,team_id_against,event,secondary_type,coord_x,coord_y,period,play_period_type,...,season,season_year,game_type,game_timestamp,winner,game_period_type,home_team_id,away_team_id,penalty_severity,penalty_minutes
0,2016020163_212,2016020163,23,10,Penalty,Hi-sticking,83,-4,2,REGULAR,...,20162017,2016,R,2016-11-05 23:00:00,home,REG,10,23,Minor,2
1,2016020163_231,2016020163,23,10,Penalty,Hooking,-54,11,2,REGULAR,...,20162017,2016,R,2016-11-05 23:00:00,home,REG,10,23,Minor,2
2,2016020163_310,2016020163,10,23,Penalty,Charging,-53,-30,3,REGULAR,...,20162017,2016,R,2016-11-05 23:00:00,home,REG,10,23,Major,5
3,2016020163_311,2016020163,10,23,Penalty,Fighting,-71,-23,3,REGULAR,...,20162017,2016,R,2016-11-05 23:00:00,home,REG,10,23,Major,5
4,2016020163_312,2016020163,23,10,Penalty,Instigator,69,24,3,REGULAR,...,20162017,2016,R,2016-11-05 23:00:00,home,REG,10,23,Minor,2

In [2]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
con.sql("SELECT * FROM main_marts.mart_penalty_cost LIMIT 10").df()

,team_id,season_year,penalty_severity,period,games_with_penalty,total_penalties,avg_penalty_minutes,pen_team_won,pen_team_lost,loss_rate_pc
0,24,2017,Minor,1,57,97,2.02,29,28,49.12
1,52,2015,Minor,1,63,105,2.04,29,34,53.97
2,20,2017,Minor,1,60,101,2.00,27,33,55.00
3,26,2015,Minor,2,69,128,2.03,36,33,47.83
4,52,2016,Major,2,9,9,5.00,4,5,55.56
5,30,2017,Minor,1,55,89,2.02,28,27,49.09
6,24,2015,Major,3,4,5,5.00,3,1,25.00
7,8,2017,Minor,1,61,89,2.02,21,40,65.57
8,8,2016,Major,3,3,3,5.00,2,1,33.33
9,24,2016,Major,3,5,8,5.00,3,2,40.00

In [2]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
con.sql("SELECT COUNT(*) FROM main_marts.mart_penalty_cost").df()

   count_star()
0          5609

In [3]:
con.sql("SELECT * FROM main_marts.mart_penalty_cost LIMIT 10").df()

,team_id,season_year,penalty_severity,period,games_with_penalty,total_penalties,avg_penalty_minutes,pen_team_won,pen_team_lost,loss_rate_pc
0,24,2017,Minor,1,57,97,2.02,29,28,49.12
1,52,2015,Minor,1,63,105,2.04,29,34,53.97
2,20,2017,Minor,1,60,101,2.00,27,33,55.00
3,26,2015,Minor,2,69,128,2.03,36,33,47.83
4,52,2016,Major,2,9,9,5.00,4,5,55.56
5,30,2017,Minor,1,55,89,2.02,28,27,49.09
6,24,2015,Major,3,4,5,5.00,3,1,25.00
7,8,2017,Minor,1,61,89,2.02,21,40,65.57
8,8,2016,Major,3,3,3,5.00,2,1,33.33
9,24,2016,Major,3,5,8,5.00,3,2,40.00

In [4]:
con.sql("SELECT COUNT(*) FROM main_marts.mart_penalty_cost").df()

   count_star()
0          5609

In [5]:
con.sql("SELECT * FROM main_marts.mart_shot_zones").df()

,team_id,season_year,total_shot_attempts,shots_on_goal,total_goals,shot_conversion_rate,goals_with_coords,goals_missing_coords,goals_missing_coords_pct
0,18,2013,4441,2159,222,10.28,222,0,0.00
1,29,2013,4733,2362,251,10.63,250,1,0.40
2,9,2013,4736,2464,240,9.74,240,0,0.00
3,14,2011,4097,1867,222,11.89,222,0,0.00
4,30,2011,4356,2010,190,9.45,190,0,0.00
...,...,...,...,...,...,...,...,...,...
602,16,2005,235,15,216,1440.00,0,216,100.00
603,28,2014,4969,2358,230,9.75,230,0,0.00
604,21,2014,4447,2073,232,11.19,231,1,0.43
605,25,2014,4721,2175,251,11.54,251,0,0.00
606,27,2007,248,19,221,1163.16,0,221,100.00

In [6]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
con.sql("SELECT * FROM main_marts.mart_shot_zones ORDER BY shot_conversion_rate DESC LIMIT 10").df()

,team_id,season_year,total_shot_attempts,shots_on_goal,total_goals,shot_conversion_rate,goals_with_coords,goals_missing_coords,goals_missing_coords_pct
0,28,2006,264,4,259,6475.00,0,259,100.0
1,12,2007,258,5,251,5020.00,0,251,100.0
2,14,2007,227,5,221,4420.00,0,221,100.0
3,20,2008,259,6,250,4166.67,0,250,100.0
4,8,2005,248,6,238,3966.67,0,238,100.0
5,17,2005,326,8,313,3912.50,0,313,100.0
6,26,2005,259,7,249,3557.14,0,249,100.0
7,23,2009,289,8,277,3462.50,0,277,100.0
8,20,2007,236,7,225,3214.29,0,225,100.0
9,1,2008,263,9,250,2777.78,0,250,100.0

In [7]:
con.sql("""
    SELECT event, team_id_for, COUNT(*) 
    FROM main_silver.fact_play 
    WHERE event = 'Goal'
    GROUP BY event, team_id_for 
    ORDER BY team_id_for
    LIMIT 20
""").df()

   event  team_id_for  count_star()
0   Goal            1          5318
1   Goal            2          5856
2   Goal            3          5961
3   Goal            4          6124
4   Goal            5          6465
5   Goal            6          6581
6   Goal            7          5426
7   Goal            8          5745
8   Goal            9          5876
9   Goal           10          6210
10  Goal           11          2293
11  Goal           12          5738
12  Goal           13          5583
13  Goal           14          6716
14  Goal           15          6506
15  Goal           16          6180
16  Goal           17          5738
17  Goal           18          5890
18  Goal           19          6190
19  Goal           20          5859

In [8]:
con.sql("""
    SELECT season_year, 
           COUNT(*) AS total_goals,
           COUNT(*) FILTER (WHERE coord_x IS NULL) AS missing_coords
    FROM main_silver.fact_play
    WHERE event = 'Goal'
    GROUP BY season_year
    ORDER BY season_year
""").df()

    season_year  total_goals  missing_coords
0          2000         5969            5969
1          2001         5610            5610
2          2002         5627            5627
3          2003         5465            5465
4          2005         7617            7617
5          2006         7365            7365
6          2007         6900            6900
7          2008         7247            7247
8          2009         7149            7149
9          2010         7376               2
10         2011         7233               3
11         2012         4411               3
12         2013         7377              11
13         2014         7243               2
14         2015         7082               0
15         2016         7251               3
16         2017         7992               5
17         2018        33000              12
18         2019        29360               0
19         <NA>         2884            2756

In [9]:
con.sql("""
    SELECT season_year, COUNT(DISTINCT game_id) AS games, COUNT(*) AS goal_events
    FROM main_silver.fact_play
    WHERE event = 'Goal'
    GROUP BY season_year
    ORDER BY season_year
""").df()

    season_year  games  goal_events
0          2000   1058         5969
1          2001   1054         5610
2          2002   1043         5627
3          2003   1039         5465
4          2005   1206         7617
5          2006   1212         7365
6          2007   1207         6900
7          2008   1211         7247
8          2009   1217         7149
9          2010   1290         7376
10         2011   1293         7233
11         2012    795         4411
12         2013   1301         7377
13         2014   1295         7243
14         2015   1287         7082
15         2016   1300         7251
16         2017   1326         7992
17         2018   1358        33000
18         2019   1212        29360
19         <NA>    601         2884

In [10]:
con.sql("""
    SELECT season_year, COUNT(DISTINCT game_id) AS games, COUNT(*) AS goal_events
    FROM main_silver.fact_play
    WHERE event = 'Goal'
    AND season_year IN (2017, 2018, 2019)
    GROUP BY season_year
""").df()

   season_year  games  goal_events
0         2017   1326         7992
1         2019   1212        29360
2         2018   1358        33000

In [11]:
con.sql("""
    SELECT COUNT(*) 
    FROM raw.game_plays 
    WHERE game_id::VARCHAR LIKE '2018%' 
    AND event = 'Goal'
""").df()

   count_star()
0         16552

In [12]:
con.sql("""
    SELECT COUNT(*) 
    FROM raw.game_plays 
    WHERE game_id::VARCHAR LIKE '2017%' 
    AND event = 'Goal'
""").df()

   count_star()
0          7992

In [13]:
con.sql("""
    SELECT play_id, COUNT(*) AS cnt
    FROM main_staging.stg_game_penalties
    WHERE play_id::VARCHAR LIKE '2018%'
    GROUP BY play_id
    HAVING COUNT(*) > 1
    ORDER BY cnt DESC
    LIMIT 10
""").df()

Empty DataFrame
Columns: [play_id, cnt]
Index: []

In [14]:
con.sql("""
    SELECT play_id, COUNT(*) AS cnt
    FROM raw.game_penalties
    WHERE play_id::VARCHAR LIKE '2018%'
    GROUP BY play_id
    HAVING COUNT(*) > 1
    ORDER BY cnt DESC
    LIMIT 10
""").df()

          play_id  cnt
0  2018020408_228    2
1   2018020410_30    2
2   2018020413_37    2
3  2018020413_268    2
4  2018020414_204    2
5  2018020417_102    2
6  2018020418_257    2
7  2018020419_182    2
8  2018020419_267    2
9  2018020420_185    2

In [1]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
con.sql("""
    SELECT season_year, COUNT(DISTINCT game_id) AS games, COUNT(*) AS goal_events
    FROM main_silver.fact_play
    WHERE event = 'Goal'
    AND season_year IN (2017, 2018, 2019)
    GROUP BY season_year
""").df()

   season_year  games  goal_events
0         2018   1358        16500
1         2019   1212        14694
2         2017   1326         7992

In [2]:
# 2. verify fact_play fixed
con.sql("""
    SELECT season_year, COUNT(DISTINCT game_id) AS games, COUNT(*) AS goal_events
    FROM main_silver.fact_play
    WHERE event = 'Goal'
    AND season_year IN (2017, 2018, 2019)
    GROUP BY season_year
""").df()

   season_year  games  goal_events
0         2017   1326         7992
1         2018   1358        16500
2         2019   1212        14694

In [3]:
con.sql("""
    SELECT COUNT(*) AS total, COUNT(DISTINCT play_id) AS unique_play_ids
    FROM main_staging.stg_game_penalties
    WHERE play_id::VARCHAR LIKE '2018%'
""").df()

   total  unique_play_ids
0   9711             9711

In [4]:
con.sql("""
    SELECT play_id, COUNT(*) AS cnt
    FROM main_staging.stg_game_plays
    WHERE play_id::VARCHAR LIKE '2018%'
    GROUP BY play_id
    HAVING COUNT(*) > 1
    ORDER BY cnt DESC
    LIMIT 10
""").df()

Empty DataFrame
Columns: [play_id, cnt]
Index: []

In [6]:
con.sql("""
    SELECT play_id, COUNT(*) AS cnt
    FROM raw.game_plays
    WHERE play_id::VARCHAR LIKE '2018%'
    GROUP BY play_id
    HAVING COUNT(*) > 1
    ORDER BY cnt DESC
    LIMIT 10
""").df()

          play_id  cnt
0  2018020031_134    2
1   2018020001_40    2
2   2018020001_57    2
3   2018020001_62    2
4   2018020001_95    2
5  2018020001_101    2
6  2018020001_107    2
7  2018020001_116    2
8  2018020032_215    2
9  2018020001_126    2

In [2]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
# 1. check stg_game_plays dedup
con.sql("""
    SELECT COUNT(*) AS total, COUNT(DISTINCT play_id) AS unique_play_ids
    FROM main_staging.stg_game_plays
    WHERE play_id::VARCHAR LIKE '2018%'
""").df()

# 2. check fact_play goal counts
con.sql("""
    SELECT season_year, COUNT(DISTINCT game_id) AS games, COUNT(*) AS goal_events
    FROM main_silver.fact_play
    WHERE event = 'Goal'
    AND season_year IN (2017, 2018, 2019)
    GROUP BY season_year
""").df()

# 3. check mart_shot_zones conversion rates
con.sql("""
    SELECT * FROM main_marts.mart_shot_zones
    ORDER BY shot_conversion_rate DESC
    LIMIT 10
""").df()

,team_id,season_year,total_shot_attempts,shots_on_goal,total_goals,shot_conversion_rate,goals_with_coords,goals_missing_coords,goals_missing_coords_pct
0,28,2006,264,4,259,6475.00,0,259,100.0
1,12,2007,258,5,251,5020.00,0,251,100.0
2,14,2007,227,5,221,4420.00,0,221,100.0
3,20,2008,259,6,250,4166.67,0,250,100.0
4,8,2005,248,6,238,3966.67,0,238,100.0
5,17,2005,326,8,313,3912.50,0,313,100.0
6,26,2005,259,7,249,3557.14,0,249,100.0
7,23,2009,289,8,277,3462.50,0,277,100.0
8,20,2007,236,7,225,3214.29,0,225,100.0
9,1,2008,263,9,250,2777.78,0,250,100.0

In [3]:
con.sql("""
    SELECT season_year, COUNT(DISTINCT game_id) AS games, COUNT(*) AS goal_events
    FROM main_silver.fact_play
    WHERE event = 'Goal'
    AND season_year IN (2017, 2018, 2019)
    GROUP BY season_year
""").df()

   season_year  games  goal_events
0         2019   1212        14694
1         2017   1326         7992
2         2018   1358        16500

In [2]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
# 1. check top conversion rates are sensible
con.sql("""
    SELECT * FROM main_marts.mart_shot_zones
    ORDER BY shot_conversion_rate DESC
    LIMIT 10
""").df()

,team_id,season_year,total_shot_attempts,shots_on_goal,total_goals,shot_conversion_rate,goals_with_coords,goals_missing_coords,goals_missing_coords_pct
0,14,2018,39640,19336,2712,14.03,2712,0,0.00
1,10,2012,2965,1273,162,12.73,162,0,0.00
2,15,2018,41784,19176,2440,12.72,2424,16,0.66
3,5,2012,3691,1729,217,12.55,217,0,0.00
4,14,2012,2431,1135,141,12.42,141,0,0.00
5,14,2017,5758,2789,343,12.30,341,2,0.58
6,15,2017,6042,2773,341,12.30,341,0,0.00
7,23,2019,40760,18784,2248,11.97,2248,0,0.00
8,20,2018,40432,20256,2424,11.97,2424,0,0.00
9,15,2019,35960,17408,2080,11.95,2080,0,0.00

In [3]:

# 2. check no pre-2010 seasons snuck in
con.sql("""
    SELECT MIN(season_year), MAX(season_year)
    FROM main_marts.mart_shot_zones
""").df()

   min(season_year)  max(season_year)
0              2010              2019

In [4]:

# 3. check row count
con.sql("SELECT COUNT(*) FROM main_marts.mart_shot_zones").df()

   count_star()
0           303

In [5]:
con.sql("SELECT * FROM main_staging.stg_game_skater_stats LIMIT 5").df()

,game_id,player_id,team_id,time_on_ice,assists,goals,points,shots,hits,pp_goals,...,sh_assists,penalty_minutes,fo_wins,fo_taken,plus_minus,takeaways,giveaways,blocked,even_time_on_ice,pp_time_on_ice
0,2016020045,8468513,4,955,1,0,1,0,2,0,...,0,0,0,0,1,1,1,1,858,0
1,2016020045,8476906,4,1396,1,0,1,4,2,0,...,0,2,0,0,0,1,2,2,1177,219
2,2016020045,8474668,4,915,0,0,0,1,1,0,...,0,0,0,0,-1,2,0,0,805,110
3,2016020045,8473512,4,1367,3,0,3,0,0,0,...,0,0,11,27,-1,0,0,0,1083,265
4,2016020045,8471762,4,676,0,0,0,3,2,0,...,0,0,0,0,-1,0,1,0,613,0

In [6]:
con.sql("DESCRIBE main_staging.stg_game_skater_stats").df()

         column_name column_type null   key default extra
0            game_id      BIGINT  YES  None    None  None
1          player_id      BIGINT  YES  None    None  None
2            team_id     INTEGER  YES  None    None  None
3        time_on_ice     INTEGER  YES  None    None  None
4            assists     INTEGER  YES  None    None  None
5              goals     INTEGER  YES  None    None  None
6             points     INTEGER  YES  None    None  None
7              shots     INTEGER  YES  None    None  None
8               hits     INTEGER  YES  None    None  None
9           pp_goals     INTEGER  YES  None    None  None
10        pp_assists     INTEGER  YES  None    None  None
11          sh_goals     INTEGER  YES  None    None  None
12        sh_assists     INTEGER  YES  None    None  None
13   penalty_minutes     INTEGER  YES  None    None  None
14           fo_wins     INTEGER  YES  None    None  None
15          fo_taken     INTEGER  YES  None    None  None
16        plus_minus     INTEGER  YES  None    None  None
17         takeaways     INTEGER  YES  None    None  None
18         giveaways     INTEGER  YES  None    None  None
19           blocked     INTEGER  YES  None    None  None
20  even_time_on_ice     INTEGER  YES  None    None  None
21    pp_time_on_ice     INTEGER  YES  None    None  None

In [11]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")

# 1. row count - masterplan expects ~15,061
con.sql("SELECT COUNT(*) FROM main_marts.mart_player_season").df()

   count_star()
0         16775

In [2]:

# 2. check top players by points_per_60
con.sql("""
    SELECT * FROM main_marts.mart_player_season
    WHERE is_underused_high_impact = true
    ORDER BY points_per_60 DESC
    LIMIT 10
""").df()

,player_id,season_year,games_played,total_goals,total_assists,total_points,total_shots,total_hits,total_pp_goals,total_sh_goals,total_penalty_minutes,total_plus_minus,total_toi_seconds,points_per_60,is_underused_high_impact
0,8467425,2001,1,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,1.0,201.0,17.91,True
1,8480068,2018,1,6.0,0.0,6.0,6.0,2.0,0.0,0.0,0.0,6.0,1364.0,15.84,True
2,8474098,2012,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.0,291.0,12.37,True
3,8476511,2016,1,1.0,0.0,1.0,1.0,2.0,0.0,0.0,2.0,1.0,318.0,11.32,True
4,8467931,2005,1,0.0,1.0,1.0,0.0,NaN,0.0,0.0,2.0,0.0,361.0,9.97,True
5,8465113,2010,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,375.0,9.60,True
6,8469132,2005,1,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,2.0,432.0,8.33,True
7,8468047,2002,1,1.0,0.0,1.0,1.0,NaN,0.0,0.0,0.0,0.0,435.0,8.28,True
8,8470809,2006,1,1.0,0.0,1.0,3.0,NaN,0.0,0.0,0.0,1.0,438.0,8.22,True
9,8474049,2011,2,2.0,1.0,3.0,3.0,6.0,0.0,0.0,12.0,3.0,1324.0,8.16,True

In [3]:

# 3. sanity check - no nulls on key columns
con.sql("""
    SELECT COUNT(*) FILTER (WHERE points_per_60 IS NULL) AS null_pp60,
           COUNT(*) FILTER (WHERE is_underused_high_impact IS NULL) AS null_flag
    FROM main_marts.mart_player_season
""").df()

   null_pp60  null_flag
0          0          0

In [4]:
con.sql("""
    SELECT DISTINCT s.game_id
    FROM main_staging.stg_game_skater_stats s
    LEFT JOIN main_staging.stg_game g
        ON s.game_id = g.game_id
    WHERE g.game_id IS NULL
""").df()

        game_id
0    2002021182
1    2002020615
2    2002020892
3    2003020713
4    2003020841
..          ...
628  2000020143
629  2002021148
630  2002020639
631  2000021199
632  2002020496

[633 rows x 1 columns]

In [5]:
con.sql("""
    SELECT game_id, type, date_time_GMT
    FROM raw.game
    WHERE game_id IN (
        SELECT DISTINCT s.game_id
        FROM main_staging.stg_game_skater_stats s
        LEFT JOIN main_staging.stg_game g
            ON s.game_id = g.game_id
        WHERE g.game_id IS NULL
    )
    LIMIT 10
""").df()

      game_id type         date_time_GMT
0  2002021013    R  2003-03-09T00:00:00Z
1  2002020776    R  2003-01-31T03:00:00Z
2  2002021123    R  2003-03-23T20:00:00Z
3  2002020853    R  2003-02-15T00:30:00Z
4  2002020270    R  2002-11-20T00:00:00Z
5  2002021199    R  2003-04-03T02:00:00Z
6  2002021177    R  2003-04-01T00:00:00Z
7  2002020547    R  2002-12-30T02:00:00Z
8  2002021211    R  2003-04-05T01:30:00Z
9  2002021023    R  2003-03-09T22:00:00Z

In [6]:
con.sql("""
    SELECT COUNT(*) 
    FROM main_staging.stg_game
    WHERE game_id IN (2003020604, 2000020038, 2000020206)
""").df()

   count_star()
0             0

In [7]:
con.sql("""
    SELECT game_id, type, outcome
    FROM raw.game
    WHERE game_id IN (2003020604, 2000020038, 2000020206)
""").df()

      game_id type     outcome
0  2003020604    R  tbc win OT
1  2000020038    R  tbc win OT
2  2000020206    R  tbc win OT

In [8]:
con.sql("""
    SELECT player_id, season_year, COUNT(*) AS team_count
    FROM main_marts.mart_player_season
    GROUP BY player_id, season_year
    HAVING COUNT(*) > 1
    ORDER BY team_count DESC
""").df()

Empty DataFrame
Columns: [player_id, season_year, team_count]
Index: []

In [10]:
con.sql("""
    SELECT player_id, game_id, COUNT(*) AS cnt
    FROM main_staging.stg_game_skater_stats
    GROUP BY player_id, game_id
    HAVING COUNT(*) > 1
""").df()

Empty DataFrame
Columns: [player_id, game_id, cnt]
Index: []

In [2]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
# 1. check dedup worked
con.sql("""
    SELECT player_id, game_id, COUNT(*) AS cnt
    FROM main_staging.stg_game_skater_stats
    GROUP BY player_id, game_id
    HAVING COUNT(*) > 1
""").df()

Empty DataFrame
Columns: [player_id, game_id, cnt]
Index: []

In [3]:
# 2. row count - should be close to 15,061
con.sql("SELECT COUNT(*) FROM main_marts.mart_player_season").df()

   count_star()
0         16775

In [4]:
# 3. check top underused high impact players
con.sql("""
    SELECT * FROM main_marts.mart_player_season
    WHERE is_underused_high_impact = true
    ORDER BY points_per_60 DESC
    LIMIT 10
""").df()

,player_id,season_year,games_played,total_goals,total_assists,total_points,total_shots,total_hits,total_pp_goals,total_sh_goals,total_penalty_minutes,total_plus_minus,total_toi_seconds,points_per_60,is_underused_high_impact
0,8467425,2001,1,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,1.0,201.0,17.91,True
1,8480068,2018,1,6.0,0.0,6.0,6.0,2.0,0.0,0.0,0.0,6.0,1364.0,15.84,True
2,8474098,2012,1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.0,291.0,12.37,True
3,8476511,2016,1,1.0,0.0,1.0,1.0,2.0,0.0,0.0,2.0,1.0,318.0,11.32,True
4,8467931,2005,1,0.0,1.0,1.0,0.0,NaN,0.0,0.0,2.0,0.0,361.0,9.97,True
5,8465113,2010,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,375.0,9.60,True
6,8469132,2005,1,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,2.0,432.0,8.33,True
7,8468047,2002,1,1.0,0.0,1.0,1.0,NaN,0.0,0.0,0.0,0.0,435.0,8.28,True
8,8470809,2006,1,1.0,0.0,1.0,3.0,NaN,0.0,0.0,0.0,1.0,438.0,8.22,True
9,8474049,2011,2,2.0,1.0,3.0,3.0,6.0,0.0,0.0,12.0,3.0,1324.0,8.16,True

In [5]:
con.sql("""
    SELECT player_id, season_year, COUNT(*) AS cnt
    FROM main_marts.mart_player_season
    GROUP BY player_id, season_year
    HAVING COUNT(*) > 1
    ORDER BY cnt DESC
    LIMIT 10
""").df()

Empty DataFrame
Columns: [player_id, season_year, cnt]
Index: []

In [1]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
con.sql("""
    SELECT MIN(games_played) AS min_games,
           MAX(games_played) AS max_games,
           COUNT(*) AS flagged_players
    FROM main_marts.mart_player_season
    WHERE is_underused_high_impact = true
""").df()

   min_games  max_games  flagged_players
0         10         88             1826

In [1]:
import duckdb
con = duckdb.connect("../nhl_raw.duckdb")
con.sql("SELECT * FROM main_staging.stg_team_info LIMIT 5").df()

   team_id  franchise_id          city  team_name abbreviation
0        1            23    New Jersey     Devils          NJD
1        4            16  Philadelphia     Flyers          PHI
2       26            14   Los Angeles      Kings          LAK
3       14            31     Tampa Bay  Lightning          TBL
4        6             6        Boston     Bruins          BOS

In [2]:
con.sql("SELECT * FROM main_staging.stg_player_info LIMIT 5").df()

,player_id,first_name,last_name,full_name,nationality,birth_city,birth_date,primary_position,height_cm,weight_kg,shoots_catches
0,8466148,Marian,Hossa,Marian Hossa,SVK,Stará Lubovna,1979-01-12,RW,185.419998,93.900002,L
1,8465058,Michal,Rozsival,Michal Rozsival,CZE,Vlasim,1978-09-03,D,185.419998,95.199997,R
2,8476906,Shayne,Gostisbehere,Shayne Gostisbehere,USA,Pembroke Pines,1993-04-20,D,180.339996,81.599998,L
3,8466285,Brian,Campbell,Brian Campbell,CAN,Strathroy,1979-05-23,D,177.800003,87.099998,L
4,8470607,Brent,Seabrook,Brent Seabrook,CAN,Richmond,1985-04-20,D,190.500000,99.800003,R

In [3]:
con.sql("SELECT * FROM main_staging.stg_game LIMIT 5").df()

,game_id,season,season_year,game_type,game_timestamp,venue,away_team_id,home_team_id,away_goals,home_goals,winner,period_type,is_tbc,is_allstar
0,2016020045,20162017,2016,R,2016-10-19 00:30:00,United Center,4,16,4,7,home,REG,False,False
1,2017020812,20172018,2017,R,2018-02-07 00:00:00,KeyBank Center,24,7,4,3,away,OT,False,False
2,2015020314,20152016,2015,R,2015-11-24 01:00:00,MTS Centre,21,52,4,1,away,REG,False,False
3,2015020849,20152016,2015,R,2016-02-17 00:00:00,PNC Arena,52,12,1,2,home,REG,False,False
4,2017020586,20172018,2017,R,2017-12-30 03:00:00,Honda Center,20,24,1,2,home,REG,False,False

In [4]:
con.sql("SELECT * FROM main_staging.stg_game_teams_stats LIMIT 5").df()

,game_id,team_id,is_home,won,settled_in,goals,shots,hits,pim,pp_opportunities,pp_goals,pp_conversion_rate,face_off_win_perc,giveaways,takeaways,start_rink_side
0,2016020045,4,False,False,REG,4,27,30,6,4,2,0.500000,50.900002,12,9,left
1,2016020045,16,True,True,REG,7,28,20,8,3,2,0.666667,49.099998,16,8,left
2,2017020812,24,False,True,OT,4,34,16,6,3,1,0.333333,43.799999,7,4,right
3,2017020812,7,True,False,OT,3,33,17,8,2,1,0.500000,56.200001,5,6,right
4,2015020314,21,False,True,REG,4,29,17,9,3,1,0.333333,45.700001,13,5,left